// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_tb_top);
    __Vhier.remove(&__Vscope_tb_top, &__Vscope_tb_top__cpu);
    __Vhier.remove(&__Vscope_tb_top__cpu, &__Vscope_tb_top__cpu__genblk1__pcpi_mul);
    __Vhier.remove(&__Vscope_tb_top__cpu, &__Vscope_tb_top__cpu__genblk2__pcpi_div);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(227);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_tb_top.configure(this, name(), "tb_top", "tb_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tb_top__cpu.configure(this, name(), "tb_top.cpu", "cpu", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tb_top__cpu__genblk1__pcpi_mul.configure(this, name(), "tb_top.cpu.genblk1.pcpi_mul", "pcpi_mul", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_tb_top__cpu__genblk2__pcpi_div.configure(this, name(), "tb_top.cpu.genblk2.pcpi_div", "pcpi_div", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_tb_top);
    __Vhier.add(&__Vscope_tb_top, &__Vscope_tb_top__cpu);
    __Vhier.add(&__Vscope_tb_top__cpu, &__Vscope_tb_top__cpu__genblk1__pcpi_mul);
    __Vhier.add(&__Vscope_tb_top__cpu, &__Vscope_tb_top__cpu__genblk2__pcpi_div);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"out_char", &(TOP.out_char), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"out_valid", &(TOP.out_valid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"resetn", &(TOP.resetn), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"trap", &(TOP.trap), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"MEM_WORDS", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__MEM_WORDS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top.varInsert(__Vfinal,"OUT_ADDR", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__OUT_ADDR))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top.varInsert(__Vfinal,"clk", &(TOP.tb_top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"hexfile", &(TOP.tb_top__DOT__hexfile), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,1023,0);
        __Vscope_tb_top.varInsert(__Vfinal,"i", &(TOP.tb_top__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_addr", &(TOP.tb_top__DOT__mem_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_instr", &(TOP.tb_top__DOT__mem_instr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_rdata", &(TOP.tb_top__DOT__mem_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_ready", &(TOP.tb_top__DOT__mem_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_valid", &(TOP.tb_top__DOT__mem_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_wdata", &(TOP.tb_top__DOT__mem_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top.varInsert(__Vfinal,"mem_wstrb", &(TOP.tb_top__DOT__mem_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_tb_top.varInsert(__Vfinal,"memory", &(TOP.tb_top__DOT__memory), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,32767);
        __Vscope_tb_top.varInsert(__Vfinal,"out_char", &(TOP.tb_top__DOT__out_char), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top.varInsert(__Vfinal,"out_valid", &(TOP.tb_top__DOT__out_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"resetn", &(TOP.tb_top__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top.varInsert(__Vfinal,"trap", &(TOP.tb_top__DOT__trap), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"BARREL_SHIFTER", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__BARREL_SHIFTER))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"CATCH_ILLINSN", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__CATCH_ILLINSN))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"CATCH_MISALIGN", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__CATCH_MISALIGN))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"COMPRESSED_ISA", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__COMPRESSED_ISA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_COUNTERS", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_COUNTERS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_COUNTERS64", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_COUNTERS64))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_DIV", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_DIV))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_FAST_MUL", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_FAST_MUL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_IRQ))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_IRQ_QREGS", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_IRQ_QREGS))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_IRQ_TIMER", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_IRQ_TIMER))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_MUL", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_MUL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_PCPI", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_PCPI))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_REGS_16_31", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_REGS_16_31))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_REGS_DUALPORT", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_REGS_DUALPORT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"ENABLE_TRACE", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__ENABLE_TRACE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"LATCHED_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__LATCHED_IRQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"LATCHED_MEM_RDATA", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__LATCHED_MEM_RDATA))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"MASKED_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__MASKED_IRQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"PROGADDR_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__PROGADDR_IRQ))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"PROGADDR_RESET", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__PROGADDR_RESET))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"REGS_INIT_ZERO", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__REGS_INIT_ZERO))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"STACKADDR", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__STACKADDR))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"TRACE_ADDR", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__TRACE_ADDR))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,35,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"TRACE_BRANCH", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__TRACE_BRANCH))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,35,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"TRACE_IRQ", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__TRACE_IRQ))), true, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,35,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"TWO_CYCLE_ALU", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__TWO_CYCLE_ALU))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"TWO_CYCLE_COMPARE", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__TWO_CYCLE_COMPARE))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"TWO_STAGE_SHIFT", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__TWO_STAGE_SHIFT))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"WITH_PCPI", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__WITH_PCPI))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_add_sub", &(TOP.tb_top__DOT__cpu__DOT__alu_add_sub), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_eq", &(TOP.tb_top__DOT__cpu__DOT__alu_eq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_lts", &(TOP.tb_top__DOT__cpu__DOT__alu_lts), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_ltu", &(TOP.tb_top__DOT__cpu__DOT__alu_ltu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_out", &(TOP.tb_top__DOT__cpu__DOT__alu_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_out_0", &(TOP.tb_top__DOT__cpu__DOT__alu_out_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_out_0_q", &(TOP.tb_top__DOT__cpu__DOT__alu_out_0_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_out_q", &(TOP.tb_top__DOT__cpu__DOT__alu_out_q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_shl", &(TOP.tb_top__DOT__cpu__DOT__alu_shl), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_shr", &(TOP.tb_top__DOT__cpu__DOT__alu_shr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_wait", &(TOP.tb_top__DOT__cpu__DOT__alu_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"alu_wait_2", &(TOP.tb_top__DOT__cpu__DOT__alu_wait_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cached_ascii_instr", &(TOP.tb_top__DOT__cpu__DOT__cached_ascii_instr), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cached_insn_imm", &(TOP.tb_top__DOT__cpu__DOT__cached_insn_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cached_insn_opcode", &(TOP.tb_top__DOT__cpu__DOT__cached_insn_opcode), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cached_insn_rd", &(TOP.tb_top__DOT__cpu__DOT__cached_insn_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cached_insn_rs1", &(TOP.tb_top__DOT__cpu__DOT__cached_insn_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cached_insn_rs2", &(TOP.tb_top__DOT__cpu__DOT__cached_insn_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"clear_prefetched_high_word", &(TOP.tb_top__DOT__cpu__DOT__clear_prefetched_high_word), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"clear_prefetched_high_word_q", &(TOP.tb_top__DOT__cpu__DOT__clear_prefetched_high_word_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"clk", &(TOP.tb_top__DOT__cpu__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"compressed_instr", &(TOP.tb_top__DOT__cpu__DOT__compressed_instr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"count_cycle", &(TOP.tb_top__DOT__cpu__DOT__count_cycle), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"count_instr", &(TOP.tb_top__DOT__cpu__DOT__count_instr), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state", &(TOP.tb_top__DOT__cpu__DOT__cpu_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_exec", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_exec))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_fetch", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_fetch))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_ld_rs1", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_ld_rs1))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_ld_rs2", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_ld_rs2))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_ldmem", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_ldmem))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_shift", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_shift))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_stmem", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_stmem))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpu_state_trap", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__cpu_state_trap))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,7,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpuregs", &(TOP.tb_top__DOT__cpu__DOT__cpuregs), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,2 ,31,0 ,0,31);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpuregs_rs1", &(TOP.tb_top__DOT__cpu__DOT__cpuregs_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpuregs_rs2", &(TOP.tb_top__DOT__cpu__DOT__cpuregs_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpuregs_wrdata", &(TOP.tb_top__DOT__cpu__DOT__cpuregs_wrdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"cpuregs_write", &(TOP.tb_top__DOT__cpu__DOT__cpuregs_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"current_pc", &(TOP.tb_top__DOT__cpu__DOT__current_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_ascii_instr", &(TOP.tb_top__DOT__cpu__DOT__dbg_ascii_instr), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_ascii_state", &(TOP.tb_top__DOT__cpu__DOT__dbg_ascii_state), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_insn_addr", &(TOP.tb_top__DOT__cpu__DOT__dbg_insn_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_insn_imm", &(TOP.tb_top__DOT__cpu__DOT__dbg_insn_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_insn_opcode", &(TOP.tb_top__DOT__cpu__DOT__dbg_insn_opcode), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_insn_rd", &(TOP.tb_top__DOT__cpu__DOT__dbg_insn_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_insn_rs1", &(TOP.tb_top__DOT__cpu__DOT__dbg_insn_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_insn_rs2", &(TOP.tb_top__DOT__cpu__DOT__dbg_insn_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_addr", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_instr", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_instr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_rdata", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_ready", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_valid", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_wdata", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_mem_wstrb", &(TOP.tb_top__DOT__cpu__DOT__dbg_mem_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_next", &(TOP.tb_top__DOT__cpu__DOT__dbg_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_rs1val", &(TOP.tb_top__DOT__cpu__DOT__dbg_rs1val), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_rs1val_valid", &(TOP.tb_top__DOT__cpu__DOT__dbg_rs1val_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_rs2val", &(TOP.tb_top__DOT__cpu__DOT__dbg_rs2val), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_rs2val_valid", &(TOP.tb_top__DOT__cpu__DOT__dbg_rs2val_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"dbg_valid_insn", &(TOP.tb_top__DOT__cpu__DOT__dbg_valid_insn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoded_imm", &(TOP.tb_top__DOT__cpu__DOT__decoded_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoded_imm_j", &(TOP.tb_top__DOT__cpu__DOT__decoded_imm_j), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoded_rd", &(TOP.tb_top__DOT__cpu__DOT__decoded_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoded_rs", &(TOP.tb_top__DOT__cpu__DOT__decoded_rs), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoded_rs1", &(TOP.tb_top__DOT__cpu__DOT__decoded_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoded_rs2", &(TOP.tb_top__DOT__cpu__DOT__decoded_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoder_pseudo_trigger", &(TOP.tb_top__DOT__cpu__DOT__decoder_pseudo_trigger), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoder_pseudo_trigger_q", &(TOP.tb_top__DOT__cpu__DOT__decoder_pseudo_trigger_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoder_trigger", &(TOP.tb_top__DOT__cpu__DOT__decoder_trigger), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"decoder_trigger_q", &(TOP.tb_top__DOT__cpu__DOT__decoder_trigger_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"do_waitirq", &(TOP.tb_top__DOT__cpu__DOT__do_waitirq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"eoi", &(TOP.tb_top__DOT__cpu__DOT__eoi), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"i", &(TOP.tb_top__DOT__cpu__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_add", &(TOP.tb_top__DOT__cpu__DOT__instr_add), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_addi", &(TOP.tb_top__DOT__cpu__DOT__instr_addi), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_and", &(TOP.tb_top__DOT__cpu__DOT__instr_and), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_andi", &(TOP.tb_top__DOT__cpu__DOT__instr_andi), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_auipc", &(TOP.tb_top__DOT__cpu__DOT__instr_auipc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_beq", &(TOP.tb_top__DOT__cpu__DOT__instr_beq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_bge", &(TOP.tb_top__DOT__cpu__DOT__instr_bge), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_bgeu", &(TOP.tb_top__DOT__cpu__DOT__instr_bgeu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_blt", &(TOP.tb_top__DOT__cpu__DOT__instr_blt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_bltu", &(TOP.tb_top__DOT__cpu__DOT__instr_bltu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_bne", &(TOP.tb_top__DOT__cpu__DOT__instr_bne), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_ecall_ebreak", &(TOP.tb_top__DOT__cpu__DOT__instr_ecall_ebreak), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_fence", &(TOP.tb_top__DOT__cpu__DOT__instr_fence), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_getq", &(TOP.tb_top__DOT__cpu__DOT__instr_getq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_jal", &(TOP.tb_top__DOT__cpu__DOT__instr_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_jalr", &(TOP.tb_top__DOT__cpu__DOT__instr_jalr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_lb", &(TOP.tb_top__DOT__cpu__DOT__instr_lb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_lbu", &(TOP.tb_top__DOT__cpu__DOT__instr_lbu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_lh", &(TOP.tb_top__DOT__cpu__DOT__instr_lh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_lhu", &(TOP.tb_top__DOT__cpu__DOT__instr_lhu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_lui", &(TOP.tb_top__DOT__cpu__DOT__instr_lui), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_lw", &(TOP.tb_top__DOT__cpu__DOT__instr_lw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_maskirq", &(TOP.tb_top__DOT__cpu__DOT__instr_maskirq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_or", &(TOP.tb_top__DOT__cpu__DOT__instr_or), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_ori", &(TOP.tb_top__DOT__cpu__DOT__instr_ori), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_rdcycle", &(TOP.tb_top__DOT__cpu__DOT__instr_rdcycle), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_rdcycleh", &(TOP.tb_top__DOT__cpu__DOT__instr_rdcycleh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_rdinstr", &(TOP.tb_top__DOT__cpu__DOT__instr_rdinstr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_rdinstrh", &(TOP.tb_top__DOT__cpu__DOT__instr_rdinstrh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_retirq", &(TOP.tb_top__DOT__cpu__DOT__instr_retirq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sb", &(TOP.tb_top__DOT__cpu__DOT__instr_sb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_setq", &(TOP.tb_top__DOT__cpu__DOT__instr_setq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sh", &(TOP.tb_top__DOT__cpu__DOT__instr_sh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sll", &(TOP.tb_top__DOT__cpu__DOT__instr_sll), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_slli", &(TOP.tb_top__DOT__cpu__DOT__instr_slli), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_slt", &(TOP.tb_top__DOT__cpu__DOT__instr_slt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_slti", &(TOP.tb_top__DOT__cpu__DOT__instr_slti), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sltiu", &(TOP.tb_top__DOT__cpu__DOT__instr_sltiu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sltu", &(TOP.tb_top__DOT__cpu__DOT__instr_sltu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sra", &(TOP.tb_top__DOT__cpu__DOT__instr_sra), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_srai", &(TOP.tb_top__DOT__cpu__DOT__instr_srai), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_srl", &(TOP.tb_top__DOT__cpu__DOT__instr_srl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_srli", &(TOP.tb_top__DOT__cpu__DOT__instr_srli), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sub", &(TOP.tb_top__DOT__cpu__DOT__instr_sub), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_sw", &(TOP.tb_top__DOT__cpu__DOT__instr_sw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_timer", &(TOP.tb_top__DOT__cpu__DOT__instr_timer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_trap", &(TOP.tb_top__DOT__cpu__DOT__instr_trap), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_waitirq", &(TOP.tb_top__DOT__cpu__DOT__instr_waitirq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_xor", &(TOP.tb_top__DOT__cpu__DOT__instr_xor), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"instr_xori", &(TOP.tb_top__DOT__cpu__DOT__instr_xori), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq", &(TOP.tb_top__DOT__cpu__DOT__irq), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_active", &(TOP.tb_top__DOT__cpu__DOT__irq_active), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_buserror", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__irq_buserror))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_delay", &(TOP.tb_top__DOT__cpu__DOT__irq_delay), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_ebreak", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__irq_ebreak))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_mask", &(TOP.tb_top__DOT__cpu__DOT__irq_mask), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_pending", &(TOP.tb_top__DOT__cpu__DOT__irq_pending), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_state", &(TOP.tb_top__DOT__cpu__DOT__irq_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irq_timer", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__irq_timer))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"irqregs_offset", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__irqregs_offset))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_alu_reg_imm", &(TOP.tb_top__DOT__cpu__DOT__is_alu_reg_imm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_alu_reg_reg", &(TOP.tb_top__DOT__cpu__DOT__is_alu_reg_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_beq_bne_blt_bge_bltu_bgeu", &(TOP.tb_top__DOT__cpu__DOT__is_beq_bne_blt_bge_bltu_bgeu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_compare", &(TOP.tb_top__DOT__cpu__DOT__is_compare), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_jalr_addi_slti_sltiu_xori_ori_andi", &(TOP.tb_top__DOT__cpu__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_lb_lh_lw_lbu_lhu", &(TOP.tb_top__DOT__cpu__DOT__is_lb_lh_lw_lbu_lhu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_lbu_lhu_lw", &(TOP.tb_top__DOT__cpu__DOT__is_lbu_lhu_lw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_lui_auipc_jal", &(TOP.tb_top__DOT__cpu__DOT__is_lui_auipc_jal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_lui_auipc_jal_jalr_addi_add_sub", &(TOP.tb_top__DOT__cpu__DOT__is_lui_auipc_jal_jalr_addi_add_sub), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_rdcycle_rdcycleh_rdinstr_rdinstrh", &(TOP.tb_top__DOT__cpu__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_sb_sh_sw", &(TOP.tb_top__DOT__cpu__DOT__is_sb_sh_sw), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_sll_srl_sra", &(TOP.tb_top__DOT__cpu__DOT__is_sll_srl_sra), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_slli_srli_srai", &(TOP.tb_top__DOT__cpu__DOT__is_slli_srli_srai), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_slti_blt_slt", &(TOP.tb_top__DOT__cpu__DOT__is_slti_blt_slt), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"is_sltiu_bltu_sltu", &(TOP.tb_top__DOT__cpu__DOT__is_sltiu_bltu_sltu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"last_mem_valid", &(TOP.tb_top__DOT__cpu__DOT__last_mem_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_branch", &(TOP.tb_top__DOT__cpu__DOT__latched_branch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_compr", &(TOP.tb_top__DOT__cpu__DOT__latched_compr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_is_lb", &(TOP.tb_top__DOT__cpu__DOT__latched_is_lb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_is_lh", &(TOP.tb_top__DOT__cpu__DOT__latched_is_lh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_is_lu", &(TOP.tb_top__DOT__cpu__DOT__latched_is_lu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_rd", &(TOP.tb_top__DOT__cpu__DOT__latched_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_stalu", &(TOP.tb_top__DOT__cpu__DOT__latched_stalu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_store", &(TOP.tb_top__DOT__cpu__DOT__latched_store), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"latched_trace", &(TOP.tb_top__DOT__cpu__DOT__latched_trace), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"launch_next_insn", &(TOP.tb_top__DOT__cpu__DOT__launch_next_insn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_16bit_buffer", &(TOP.tb_top__DOT__cpu__DOT__mem_16bit_buffer), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_addr", &(TOP.tb_top__DOT__cpu__DOT__mem_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_busy", &(TOP.tb_top__DOT__cpu__DOT__mem_busy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_do_prefetch", &(TOP.tb_top__DOT__cpu__DOT__mem_do_prefetch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_do_rdata", &(TOP.tb_top__DOT__cpu__DOT__mem_do_rdata), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_do_rinst", &(TOP.tb_top__DOT__cpu__DOT__mem_do_rinst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_do_wdata", &(TOP.tb_top__DOT__cpu__DOT__mem_do_wdata), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_done", &(TOP.tb_top__DOT__cpu__DOT__mem_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_instr", &(TOP.tb_top__DOT__cpu__DOT__mem_instr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_addr", &(TOP.tb_top__DOT__cpu__DOT__mem_la_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_firstword", &(TOP.tb_top__DOT__cpu__DOT__mem_la_firstword), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_firstword_reg", &(TOP.tb_top__DOT__cpu__DOT__mem_la_firstword_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_firstword_xfer", &(TOP.tb_top__DOT__cpu__DOT__mem_la_firstword_xfer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_read", &(TOP.tb_top__DOT__cpu__DOT__mem_la_read), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_secondword", &(TOP.tb_top__DOT__cpu__DOT__mem_la_secondword), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_use_prefetched_high_word", &(TOP.tb_top__DOT__cpu__DOT__mem_la_use_prefetched_high_word), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_wdata", &(TOP.tb_top__DOT__cpu__DOT__mem_la_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_write", &(TOP.tb_top__DOT__cpu__DOT__mem_la_write), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_la_wstrb", &(TOP.tb_top__DOT__cpu__DOT__mem_la_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_rdata", &(TOP.tb_top__DOT__cpu__DOT__mem_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_rdata_latched", &(TOP.tb_top__DOT__cpu__DOT__mem_rdata_latched), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_rdata_latched_noshuffle", &(TOP.tb_top__DOT__cpu__DOT__mem_rdata_latched_noshuffle), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_rdata_q", &(TOP.tb_top__DOT__cpu__DOT__mem_rdata_q), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_rdata_word", &(TOP.tb_top__DOT__cpu__DOT__mem_rdata_word), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_ready", &(TOP.tb_top__DOT__cpu__DOT__mem_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_state", &(TOP.tb_top__DOT__cpu__DOT__mem_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_valid", &(TOP.tb_top__DOT__cpu__DOT__mem_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_wdata", &(TOP.tb_top__DOT__cpu__DOT__mem_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_wordsize", &(TOP.tb_top__DOT__cpu__DOT__mem_wordsize), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_wstrb", &(TOP.tb_top__DOT__cpu__DOT__mem_wstrb), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"mem_xfer", &(TOP.tb_top__DOT__cpu__DOT__mem_xfer), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"new_ascii_instr", &(TOP.tb_top__DOT__cpu__DOT__new_ascii_instr), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"next_insn_opcode", &(TOP.tb_top__DOT__cpu__DOT__next_insn_opcode), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"next_irq_pending", &(TOP.tb_top__DOT__cpu__DOT__next_irq_pending), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"next_pc", &(TOP.tb_top__DOT__cpu__DOT__next_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_div_rd", &(TOP.tb_top__DOT__cpu__DOT__pcpi_div_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_div_ready", &(TOP.tb_top__DOT__cpu__DOT__pcpi_div_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_div_wait", &(TOP.tb_top__DOT__cpu__DOT__pcpi_div_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_div_wr", &(TOP.tb_top__DOT__cpu__DOT__pcpi_div_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_insn", &(TOP.tb_top__DOT__cpu__DOT__pcpi_insn), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_int_rd", &(TOP.tb_top__DOT__cpu__DOT__pcpi_int_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_int_ready", &(TOP.tb_top__DOT__cpu__DOT__pcpi_int_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_int_wait", &(TOP.tb_top__DOT__cpu__DOT__pcpi_int_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_int_wr", &(TOP.tb_top__DOT__cpu__DOT__pcpi_int_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_mul_rd", &(TOP.tb_top__DOT__cpu__DOT__pcpi_mul_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_mul_ready", &(TOP.tb_top__DOT__cpu__DOT__pcpi_mul_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_mul_wait", &(TOP.tb_top__DOT__cpu__DOT__pcpi_mul_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_mul_wr", &(TOP.tb_top__DOT__cpu__DOT__pcpi_mul_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_rd", &(TOP.tb_top__DOT__cpu__DOT__pcpi_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_ready", &(TOP.tb_top__DOT__cpu__DOT__pcpi_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_rs1", &(TOP.tb_top__DOT__cpu__DOT__pcpi_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_rs2", &(TOP.tb_top__DOT__cpu__DOT__pcpi_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_timeout", &(TOP.tb_top__DOT__cpu__DOT__pcpi_timeout), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_timeout_counter", &(TOP.tb_top__DOT__cpu__DOT__pcpi_timeout_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_valid", &(TOP.tb_top__DOT__cpu__DOT__pcpi_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_wait", &(TOP.tb_top__DOT__cpu__DOT__pcpi_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"pcpi_wr", &(TOP.tb_top__DOT__cpu__DOT__pcpi_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"prefetched_high_word", &(TOP.tb_top__DOT__cpu__DOT__prefetched_high_word), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"q_ascii_instr", &(TOP.tb_top__DOT__cpu__DOT__q_ascii_instr), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"q_insn_imm", &(TOP.tb_top__DOT__cpu__DOT__q_insn_imm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"q_insn_opcode", &(TOP.tb_top__DOT__cpu__DOT__q_insn_opcode), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"q_insn_rd", &(TOP.tb_top__DOT__cpu__DOT__q_insn_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"q_insn_rs1", &(TOP.tb_top__DOT__cpu__DOT__q_insn_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"q_insn_rs2", &(TOP.tb_top__DOT__cpu__DOT__q_insn_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"reg_next_pc", &(TOP.tb_top__DOT__cpu__DOT__reg_next_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"reg_op1", &(TOP.tb_top__DOT__cpu__DOT__reg_op1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"reg_op2", &(TOP.tb_top__DOT__cpu__DOT__reg_op2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"reg_out", &(TOP.tb_top__DOT__cpu__DOT__reg_out), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"reg_pc", &(TOP.tb_top__DOT__cpu__DOT__reg_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"reg_sh", &(TOP.tb_top__DOT__cpu__DOT__reg_sh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"regfile_size", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__regfile_size))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"regindex_bits", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__regindex_bits))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"resetn", &(TOP.tb_top__DOT__cpu__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"set_mem_do_rdata", &(TOP.tb_top__DOT__cpu__DOT__set_mem_do_rdata), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"set_mem_do_rinst", &(TOP.tb_top__DOT__cpu__DOT__set_mem_do_rinst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"set_mem_do_wdata", &(TOP.tb_top__DOT__cpu__DOT__set_mem_do_wdata), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"timer", &(TOP.tb_top__DOT__cpu__DOT__timer), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"trace_data", &(TOP.tb_top__DOT__cpu__DOT__trace_data), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,35,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"trace_valid", &(TOP.tb_top__DOT__cpu__DOT__trace_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu.varInsert(__Vfinal,"trap", &(TOP.tb_top__DOT__cpu__DOT__trap), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"CARRY_CHAIN", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__CARRY_CHAIN))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"STEPS_AT_ONCE", const_cast<void*>(static_cast<const void*>(&(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__STEPS_AT_ONCE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"clk", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"i", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_any_mul", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_any_mul), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_any_mulh", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_any_mulh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_mul", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mul), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_mulh", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulh), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_mulhsu", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulhsu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_mulhu", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulhu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_rs1_signed", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_rs1_signed), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"instr_rs2_signed", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__instr_rs2_signed), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"j", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__j), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"mul_counter", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__mul_counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"mul_finish", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__mul_finish), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"mul_start", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__mul_start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"mul_waiting", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__mul_waiting), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"next_rd", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__next_rd), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"next_rdt", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__next_rdt), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"next_rdx", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__next_rdx), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"next_rs1", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__next_rs1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"next_rs2", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__next_rs2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_insn", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_insn), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_rd", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_ready", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_rs1", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_rs2", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_valid", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_wait", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_wait_q", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_wait_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"pcpi_wr", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"rd", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__rd), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"rdx", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__rdx), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"resetn", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"rs1", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__rs1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"rs2", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__rs2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk1__pcpi_mul.varInsert(__Vfinal,"this_rs2", &(TOP.tb_top__DOT__cpu__DOT__genblk1__DOT__pcpi_mul__DOT__this_rs2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"clk", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"dividend", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__dividend), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"divisor", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__divisor), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,62,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"instr_any_div_rem", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__instr_any_div_rem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"instr_div", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__instr_div), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"instr_divu", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__instr_divu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"instr_rem", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__instr_rem), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"instr_remu", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__instr_remu), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"outsign", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__outsign), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_insn", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_insn), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_rd", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_rd), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_ready", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_rs1", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_rs1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_rs2", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_rs2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_valid", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_wait", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_wait), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_wait_q", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_wait_q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"pcpi_wr", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"quotient", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__quotient), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"quotient_msk", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__quotient_msk), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"resetn", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"running", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__running), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_tb_top__cpu__genblk2__pcpi_div.varInsert(__Vfinal,"start", &(TOP.tb_top__DOT__cpu__DOT__genblk2__DOT__pcpi_div__DOT__start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
    }
}
